FROM ubuntu as builder

WORKDIR /app

COPY * /app

RUN apt-get update && apt-get install -y openssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /app/key.pem -out /app/cert.pem -subj "/C=CO/ST=Colombia/L=San marcos/O=Caso2/CN=darwin.cerpa1.com"

FROM nginx:alpine

COPY --from=builder /app/index.html /usr/share/nginx/html

COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/*.pem /etc/nginx/
