# Usar la imagen oficial de Node.js como base
FROM docker.io/node:20.11.1-alpine3.19

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar el archivo package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias de la aplicación
RUN npm install


# Copiar el resto de la aplicación
COPY . .
# Exponer el puerto en el que la aplicación se ejecuta
EXPOSE 4000

# Comando para ejecutar la aplicación cuando se inicie el contenedor
CMD ["node", "index.js"]
