---
- name: Install Podman
  hosts: vm_1
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: installing podman
      apt:
        name: "podman"
        state: present
